"""add language to posts

Revision ID: 21471ec9055e
Revises: 991506d5be4b
Create Date: 2025-10-03 14:09:41.598869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21471ec9055e'
down_revision = '991506d5be4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
